shell = "C:\\Program Files\\PowerShell\\7\\pwsh.exe"

[window]
position = { x = 350, y = 125 }
dimensions = { columns = 128, lines = 36 }
opacity = 0.95
decorations_theme_variant = "Dark"

[scrolling]
history = 12000

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
size = 11.25

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Home"

[colors.primary]
background = "#191828"